### ISSUE TITLE
ccnet-server can't start up due to the binding of unix socket fails.

### ISSUE THREAD

**Issue by LeonSin** [haiwen/seafile-vagrant#2]
When I run this command 

```
fab runserver
```

ccnet.log will show the following:

```
./common/session.c(442): failed to bind unix socket fd to /vagrant/data/ccnet/ccnet.sock : Operation not permitted
```

It seems that  ccnet-server can't bind unix socket on  shared filesystem? Could you give me any suggestions? Thanks in advance.

**Comment by lins05** [comment]
Yeah, you may add this in your ccnet.conf:

[Client]
PORT = 13418
UNIX_SOCKET=/tmp/ccnet.sock

Shuai

**Comment by LeonSin** [comment]
> Yeah, you may add this in your ccnet.conf:
> 
> [Client]
> PORT = 13418
> UNIX_SOCKET=/tmp/ccnet.sock
> 
> Shuai

Great, it works!
Thank you.

**Comment by Tonghaofeng** [comment]
> Yeah, you may add this in your ccnet.conf:
> 
> [Client]
> PORT = 13418
> UNIX_SOCKET=/tmp/ccnet.sock
> 
> Shuai
> 
> On Sun, Jun 7, 2015 at 4:22 PM, Leon [notifications@github.com](https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=notifications@github.com) wrote:
> 
> > When I run this command
> > fab runserver
> > ccnet.log will show the following:
> > ./common/session.c(442): failed to bind unix socket fd to /vagrant/data/ccnet/ccnet.sock : Operation not permitted
> > It seems that ccnet-server can't bind unix socket on shared filesystem?
> > Could you give me any suggestions? Thanks in advance.
> > —
> > Reply to this email directly or view it on GitHub
> > #2.

just work fine with me! thanks a lot
